### ISSUE TITLE
What direction should we take, re: Thomasville Road path?

### ISSUE THREAD

**Issue by shelbygreen** [Open-Data-Tallahassee/vision-zero#11]
From @whanley:

I put the last three years into Tableau to take a rough look. Benji was right that we might find things we don't expect. What I saw is that Thomasville for some reason has almost no incident reports (see screenshot attached). I am VERY curious to understand the reasons for this--I can think of some hypotheses and it would be fun to explore it. (The age question you raise is very good btw). 

BUT--the upshot is that I don't think that the Thomasville debate is a winning venue in which to use this dataset. I think after looking at it that we should not focus our energy here. Other kinds of evidence are necessary for that debate. Also this allows us to dodge time pressure. But what do you think?

![image](https://user-images.githubusercontent.com/53214352/141303961-1129f3dd-8e96-4e55-9316-dc31d21a7dc6.png)

**Comment by shelbygreen** [comment]
Yeah, that's really interesting. Looks like we'll have to modify our hypothesis. 

Looking at the map makes me wonder how true this dataset is. How many crashes, or near crashes, happen that aren't reported? I was almost hit and killed by a driver running a red light, but because no crash actually occurred, the incident wasn't reported. I wonder if this is a gap Open Tallahassee can fill. Offering some forum to record near misses. 

TPD won a $50,000 grant to encourage seatbelt enforcement and cited "284 crashes occurred since 2020" as motivation to apply. About 264 ped/bike crashes have occurred since 2020. Maybe we could quantify the result of crashes. Some will say "oh, only 264 crashes?" but how many resulted in injuries or fatalities (in comparison to the seatbelt-related crashes)? Or how expensive was the bill? Are people still paying off medical debt?

Lots of questions and directions we can go. 

For now, I'll move forward with making the front-end for the map. Here's a [simple prototype of all crashes, 2018 - 2020](https://codepen.io/shelby-green/pen/ZEOOWrO). There's about 32,000 crashes. 400 dots are missing because their lat/long need to be corrected. After this, I would like to relate it to the other database to show the result of each crash (and age/demographics of victims). 

As we build this map, and add relevant data sources, we need to think about how to communicate this information to humanize victims. The mass amount of points could be too overwhelming for people to understand the severity of this problem.

**Comment by shelbygreen** [comment]
From Caleb:

The lack of data on Thomasville and Cap Cir NE for that matter is very curious. Especially when compared to how much is available for the West and South (if we call the the NE portion of the screenshot). To me that really screams there is some data missing. I find it hard to believe that CC doesn't look like Monroe over the same period of time if for no other reason than the sheer volume of traffic.

**Comment by shelbygreen** [comment]
It seems like doubts are being raised, which is making me question the validity of the dataset. Is it possible there's (disproportionate) under-reporting? One way we could check is if we collected our own data and compared it to the crash dataset. There's been a thread of under-reporting suggest by the Tallahassee Democrat.

**Comment by whanley** [comment]
The prototype looks great, Shelby.

The most obvious explanation (which may or may not be the right one) is that very few cyclists and pedestrians use Thomasville because it's so terrible, thus there are very few crashes. There are certainly plenty of car crashes, so I would be surprised if there's some kind of undercount.

I think that making fields to link incidents to external reports will help to corroborate the dataset.

Also, we'll want to create a form to allow people to submit missing incidents. We could use the essential fields from the dataset we have.

**Comment by shelbygreen** [comment]
Heard. Closing this thread for now because a direction has been defined: build the front-end of the map for all crashes, but include a form to allow incident submittals and possibly the ability to link outside materials to crashes on the map.
