### ISSUE TITLE
Sketch design for the demo

### ISSUE THREAD

**Issue by shelbygreen** [Open-Data-Tallahassee/vision-zero#3]
![IMG_0325C20DD29E-1](https://user-images.githubusercontent.com/53214352/138183321-d963585b-7353-46cd-87c5-da6be1c29560.jpeg)

@whanley, this is the initial design. How do you feel about it? It's simple and manageable. I'm imagining it would [follow this kind of style](https://edsource.org/dataviz/LACountyApprovals111020/).

**Comment by whanley** [comment]
Looks great!
