### ISSUE TITLE
Create dataset for 2018-2021 crashes

### ISSUE THREAD

**Issue by shelbygreen** [Open-Data-Tallahassee/vision-zero#7]
Goal: create a dataset for crashes in Leon County between 2018 and 2021. 

Process:
- remove pre-2018 crashes from the leon-events dataset
- clean it to remove rows with missing/incorrect latitude and/or longitude
- create csv file and upload it

**Comment by whanley** [comment]
I've corrected lat/long data in the full events file I just uploaded. There are lots of blanks for 2010-2017, however.

**Comment by whanley** [comment]
So here's a problem:

<img width="977" alt="Screen Shot 2021-11-13 at 2 35 13 PM" src="https://user-images.githubusercontent.com/7728326/141656851-5c1e5ff6-f925-4038-8f9a-0f0f2f38a152.png">

Not sure why there's such an low count in 2015. And the much lower counts in 2011 and 2012 are a clue about how this data comes into the system--obviously we seem to be missing some stuff.

**Comment by whanley** [comment]
This is clearer

<img width="978" alt="Screen Shot 2021-11-13 at 2 39 45 PM" src="https://user-images.githubusercontent.com/7728326/141656983-26b31f28-4b07-4515-a1d7-d52d40d40c7b.png">

**Comment by shelbygreen** [comment]
I definitely think this dataset is going to need some exploration. If we could, I'd like to try to validate it somehow. Once we add filters to the map, we can starting breaking it down by year, crash type, etc. to understand where these discrepancies are coming from. We'll also have to compare it to city policies to see if they've had any influence on the crash numbers
